import { ClerkProvider, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, Roboto, Slabo_27px } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav/Nav";

const slabo = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={slabo.className}>
          <Nav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
