import type { Metadata } from "next";
import "../globals.css";
import Nav from "@/components/Nav/Nav";
import SideBar from "@/components/SideBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
      <Nav />
      <div>
        <SideBar />
        {children}
      </div>
    </body>
  );
}
